---
- name: NETWORK CONFIGURATION
  hosts: router
  gather_facts: false
  vars:
    ansible_user: admin
    ansible_password: cisco123
    ansible_become: yes
    ansible_become_password: cisco123
    ansible_connection: network_cli

  tasks:
    - name: SETUP G0/0/1
      ios_config:
        parents: "interface GigabitEthernet0/0/1"
        lines:
            - description Interface made with Ansible
            - ip address 192.168.30.1 255.255.255.0
            - no shutdown

    - name: SHOW IP INTERFACE
      ios_command:
        commands:
            - show ip interface brief
      register: output

    - name: SAVE OUTPUT OF ROUTER CHANGE
      copy:
        content: "{{  output.stdout[0]  }}"
        dest: "ios_configurations/gig1_ouput_{{  inventory_hostname  }}.txt"
