---
- name: Create VLANs on switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Create VLAN 101 (Management)
      ios_config:
        lines:
          - vlan 101
          - name Management

    - name: Create VLAN 102 (Test)
      ios_config:
        lines:
          - vlan 102
          - name Test

    - name: Configure VLAN 101 interface
      ios_config:
        lines:
          - interface vlan 101
          - ip address 192.168.101.2 255.255.255.0
          - no shutdown

    - name: Configure VLAN 102 interface
      ios_config:
        lines:
          - interface vlan 102
          - ip address 192.168.102.2 255.255.255.0
          - no shutdown
