---
- name: Create VLANs on switches
  hosts: switch
  gather_facts: false
  vars:
    ansible_user: admin
    ansible_password: cisco123
    ansible_become: yes
    ansible_become_password: cisco123
    ansible_connection: network_cli
  
  tasks:
    - name: Create VLAN 102 (Test)
      ios_config:
        lines:
          - vlan 102
          - name Test
    
    - name: Create VLAN 103 (Test2)
      ios_config:
        lines:
          - vlan 103
          - name Test2

    - name: Configure VLAN 102 interface
      ios_config:
        lines:
          - interface vlan 102
          - ip address 192.168.102.2 255.255.255.0
          - no shutdown

    - name: Configure VLAN 103 interface
      ios_config:
        lines:
          - interface vlan 103
          - ip address 192.168.103.2 255.255.255.0
          - no shutdown