---
- name: Backup running configuration of Cisco devices
  hosts: all
  gather_facts: false
  vars:
    ansible_user: admin
    ansible_password: cisco123
    ansible_become: yes
    ansible_become_password: cisco123
    ansible_connection: network_cli
  
  tasks:
    - name: DISPLAY RUNNING_CONFIG
      ios_command:
        commands:
          - show running-config
      register: config

    - name: SAVE OUTPUT TO ./backups/
      copy:
        content: "{{ config.stdout[0] }}"   
        dest: "backups/show_run_{{ inventory_hostname }}.txt"  